version: '3'
services:
  db:
    image: mysql
    container_name: mysql-testepratico-dario
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    networks:
      - testepratico
    environment:
      MYSQL_ROOT_PASSWORD: 112233
      MYSQL_PASSWORD: 112233
      MYSQL_DATABASE: teste_pratico_dario
      MYSQL_USER: root

  api:
    image:  dariosantos/ubuntu_nginx_php72:1.5
    container_name: api-testepratico-dario
    working_dir: /var/www/html
    links:
      - db:mysql-testepratico-dario
    volumes:
      - ./:/var/www/html
      - ./default:/etc/nginx/sites-available/default
    ports:
      - 9010:80
    restart: always
    stdin_open: true
    tty: true
    networks:
      - testepratico

networks:
  testepratico:
